### ISSUE TITLE
Will this repository be maintained?

### ISSUE THREAD

**Issue by vaaaaanquish** [davechallis/rust-xgboost#12]
@davechallis @jonathanstrong Hi.

Do you have any plans to continue maintaining this repository?

I'm working on LightGBM's rust bindings. 
https://github.com/vaaaaanquish/lightgbm-rs
I have an issue where I want to integrate the interface with XGBoost.

If the maintenance continues, I can provide some pull requests.
I have the energy to take over as maintainer if you want.

Please provide a policy. I am waiting for a good answer :)

**Comment by davechallis** [comment]
@vaaaaanquish hi, and thanks for the pull requests! Sorry about the delay in replying I've just got back from a long holiday.

I'm planning to keep maintaining the repository, so happy to accept pull requests (I'll try and review/merge them later this week, hopefully on Friday).

Also happy to add you as a collaborator on this repo, if you're keen to work on it. I'm crazy busy with work at the moment, so not had much time for open source work.

**Comment by vaaaaanquish** [comment]
@davechallis Thx. Looks good to me :) I'm keen to work for `rust-xgboost`

**Comment by davechallis** [comment]
@vaaaaanquish I've reviewed the pull request, looks good to me. I've added you as a collaborator now, any problems, let me know!
