### ISSUE TITLE
Update to use xgboost 0.82

### ISSUE THREAD

**Issue by davechallis** [davechallis/rust-xgboost#2]
Release notes: https://github.com/dmlc/xgboost/blob/master/NEWS.md#v082-20190303

**Comment by liufuyang** [comment]
Is this repo still maintained? Looks like xgboost 1.0.0 is about to be out. It would be nice if this binding can be updated with it ? :)

**Comment by davechallis** [comment]
@liufuyang yup, still maintaining this repo, though haven't been keeping up with the pace of development in xgboost recently.

Will definitely update for 1.0.0 though, should have some time coming up to start building against the snapshot release.

**Comment by liufuyang** [comment]
Thank you, sounds great, I will keep an eye on this then 👍

**Comment by davechallis** [comment]
Superseded by https://github.com/davechallis/rust-xgboost/issues/8
